### PR TITLE
Some consistency fixes

### PR DESCRIPTION
**Pull request by Jojo-Schmitz**
Result of me looking at https://musescore.org/en/node/334193, but **not** fixing that at all.

### CODE REVIEW

**Comment by jeetee** [comment]
For some reason I didn't get a notify for this PR..
Will merge and streamline it in when tackling #2

**Comment by Jojo-Schmitz** [comment]
Meanwhile I'll rebase it ;-)

**Comment by jeetee** [comment]
The MS4 part is mainly blocked by https://github.com/musescore/MuseScore/issues/13593

**Comment by Jojo-Schmitz** [comment]
I know...

**Comment by jeetee** [comment]
Thanks for the hints, updated master to 4.0.0 with some workaround stuff for opening a file which is far from ideal.
I did it in parallel on my machine so you're getting zero recognition for giving me part of the push ;-)

**Comment by Jojo-Schmitz** [comment]
I'll survive ;-)

**Pull request closed without merging**
